### PR TITLE
Add missing backup/restore API methods (#20)

### PR DESCRIPTION
**Pull request by adpe**
Hi @JesGor 

It seems that the missing part is really easy to fix, so that duplication and backup&restore will work. Please check out, if I implemented the stuff with the `submissionid` correct.

Feel free, to add new commits to this PR and to merge it!

HTH,
Adrian

### CODE REVIEW

**Comment by JesGor** [comment]
Hi @adpe ,

thanks for the input, we will take a look as soon as possible and make a series of testing to check everything is working and will not affect other customers behaviour.

**Comment by adpe** [comment]
I think it will make things work instead of breaking them.

Because doing a backup at the moment, afterwards in the `backup.mbz` under `activities/assign<id>/module.xml` isn't any plagscan configuration exported at the moment. And this configuration data is needed when doing the restore to copy that. You can crosscheck that behavior with the `plagiarism/urkund` which has it implemented correct.

And the same methods will be used when doing the `duplication` process.

HTH,
Adrian

**Comment by adpe** [comment]
HI @JesGor 

Any updates for that pull request? It's very crucial and I hope you understand why.

Greets,
Adrian

**Comment by JesGor** [comment]
Hi @adpe 

please check our last commit to the branch ffhs-issue-20:

https://github.com/PlagScan/PlagScan_moodle/commit/283189bc9850c129b7b03ab480f1a2c9812f286d

We made some changes because the assignment was not created with all the data from the parent one. 

Could you test it and tell us if works for you?

Thanks,
Jesús.

**Comment by adpe** [comment]
Hi @JesGor 

Normally all the data is processed by the backup and restore functions in core moodle within the `XML` files in the backup `.mbz`. You don't must need manually to get mising data with `$DB->get_record` within the restore method. If this is the case, we are missing to put this data out to the `.mbz` file in the backup method. https://github.com/PlagScan/PlagScan_moodle/blob/283189bc9850c129b7b03ab480f1a2c9812f286d/backup/moodle2/backup_plagiarism_plagscan_plugin.class.php#L86-L98

Please check out carefully how other plugins have this implemented e.g `Urkund plagiarism` (https://github.com/danmarsden/moodle-plagiarism_urkund/tree/main/backup/moodle2).

Thanks for pay attention to that,
Adrian

**Comment by JesGor** [comment]
Hi @adpe 

We made some adaptations so the data that we needed is now also passed over the backup/restore process itself without needing to use `$DB`.

Please check the last commit in the branch: https://github.com/PlagScan/PlagScan_moodle/commit/fa7eb8f0f9391354538967cf3316472929061e02

Thanks,
Jesús.

**Comment by adpe** [comment]
Thanks for working on it @JesGor.

For me I can not follow why you must pass the `$data` in the `get_submissionid_from_plagscan` method. And why do you remove the method `$config = plagscan_get_instance_config($cmid, false);` to get the data for create after the new submission?

Also for me it doesn't make sense to write out the `cm` value to the nested backup element. As this can be taken from `$this->task->get_moduleid();`. Or it's different?

I can further not understand, what's the difference in due of this change:
https://github.com/PlagScan/PlagScan_moodle/blob/fa7eb8f0f9391354538967cf3316472929061e02/backup/moodle2/restore_plagiarism_plagscan_plugin.class.php#L86-L92. As the `cm` remains the same. It doesn't matter if you get the submissionid or not.

Can you please show what is wrong with the initial solution?

But anyways... Tomorrow I'll test your code and checkout what are the differences to the initial solution. Maybe it will be than clearer for me.

Greets,
Adrian

**Comment by adpe** [comment]
Hi @JesGor 

I understand not what was missing. And I think you don't must include `cm` value in the backup process. It's not the Moodle way to do it.

As I saw, the `$module` was always false before, as the entry for the new assignment is not yet in the `mdl_assign` table - it will be there after the restore process. Therefore I adapt it like you want to achieve it (see commit https://github.com/PlagScan/PlagScan_moodle/pull/21/commits/aabc9678fa8a001d6e8377f03f51074e5655c6c8
), that you fetch this `module data` from the old entry (where you are copying from).

Further, I don't pass the whole `data` from the restore process to this `get_submissionid_from_plagscan`. This is really PlagScan specific and therefore I use there the method `plagscan_get_instance_config` to get the data from the old config entry. Normally `$data` and the needed `$config` contain the same values, when your function `plagscan_get_instance_config` is doing what it should. But it's more PlagScan specific and the better way for me.

I think it's important don't change too much in the `$data` array used in the restore process. And the only thing we do is to assign the `submissionid` if `multiaccount` is needed. All the rest of this logic is in the `get_submissionid_from_plagscan function and processed the PlagScan way.

For me this is the cleaner solution, as we don't include the `cm` in the backup files. I think this can lead to misbehaviour in Moodle core.

Check out the recent changes and I hope it fixes your mentioned issue with the `submissionid`.

HTH,
Adrian

**Comment by adpe** [comment]
Other important question @JesGor 

I saw right now, that  the `submissionid` can be the same on multiple entries, when you change back from `multiaccount` to only one account. So when I copy a existing entry with a `submissionid` which is not `null`, it will copy the submissionid from this activity.

image

Should we add some logic, that if `multiaccount` is not enabled the submissionid will always `null` on the database? Or it's okay like that?

Greets,
Adrian

**Comment by JesGor** [comment]
Hi @adpe 

alright, we followed all your feedback and we think we could have a solution finally.

Let me answer to some of your messages:
 

> Thanks for working on it @JesGor.
> 
> For me I can not follow why you must pass the `$data` in the `get_submissionid_from_plagscan` method. And why do you remove the method `$config = plagscan_get_instance_config($cmid, false);` to get the data for create after the new submission?
> 
> Also for me it doesn't make sense to write out the `cm` value to the nested backup element. As this can be taken from `$this->task->get_moduleid();`. Or it's different?
> 
> I can further not understand, what's the difference in due of this change:
> https://github.com/PlagScan/PlagScan_moodle/blob/fa7eb8f0f9391354538967cf3316472929061e02/backup/moodle2/restore_plagiarism_plagscan_plugin.class.php#L86-L92
> 
> . As the `cm` remains the same. It doesn't matter if you get the submissionid or not.
> Can you please show what is wrong with the initial solution?
> 
> But anyways... Tomorrow I'll test your code and checkout what are the differences to the initial solution. Maybe it will be than clearer for me.
> 
> Greets,
> Adrian

The reason why we were passing `$data` to the method was to not do another call to the database to get the data that we already have in `$data` and it is what we need. As you said there is no need to use `$DB`. 

Also, the reason to send the `cm` on the backup process was because we get some module information (like title), and with the new one could not be used because it was not created yet during the restore process.

Now I see that with your solution you could find a way to do it, and is working as expected so that's great!

> Other important question @JesGor
> 
> I saw right now, that the `submissionid` can be the same on multiple entries, when you change back from `multiaccount` to only one account. So when I copy a existing entry with a `submissionid` which is not `null`, it will copy the submissionid from this activity.
> 
> image
> 
> Should we add some logic, that if `multiaccount` is not enabled the submissionid will always `null` on the database? Or it's okay like that?
> 
> Greets,
> Adrian

We added a line to set `submissionid` to `null` in case `multiaccount` is not enabled, because different assignments should not have same `submissionid`.

We merged your latest code with this new code and you can find it here: 

https://github.com/PlagScan/PlagScan_moodle/commit/3e0d2037da378cd47b9190f9af2e7e0653630880

Please if you could give a try and confirm is working and matches your requirements.

Thanks again,
Jesús.

**Comment by adpe** [comment]
Hi @JesGor 

Actually I don't have time to review, but as I see you took the base of our rebased branch, and you added the missing line in due of the `submissionid` in case `multiaccount` is not used.

Thanks for merging e.g. closing the pull request and to add this functionality to your plugin,
Adrian

**Pull request merged**
